apiVersion: apps/v1
kind: Deployment
metadata:
  name: acceptor1
  namespace: paxos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acceptor1
  template:
    metadata:
      labels:
        app: acceptor1
        role: acceptor
    spec:
      containers:
      - name: acceptor
        image: paxos-node:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ID
          value: "4"
        - name: NODE_ROLE
          value: "acceptor"
        - name: PORT
          value: "4001"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          value: "paxos"
        - name: SEED_NODES
          value: "1:proposer:proposer1.paxos.svc.cluster.local:3001"
        ports:
        - containerPort: 4001
          name: api
        - containerPort: 8000
          name: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: acceptor1
  namespace: paxos
spec:
  selector:
    app: acceptor1
  ports:
  - name: api
    port: 4001
    targetPort: api
  - name: monitor
    port: 8000
    targetPort: monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acceptor2
  namespace: paxos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acceptor2
  template:
    metadata:
      labels:
        app: acceptor2
        role: acceptor
    spec:
      containers:
      - name: acceptor
        image: paxos-node:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ID
          value: "5"
        - name: NODE_ROLE
          value: "acceptor"
        - name: PORT
          value: "4002"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          value: "paxos"
        - name: SEED_NODES
          value: "1:proposer:proposer1.paxos.svc.cluster.local:3001,4:acceptor:acceptor1.paxos.svc.cluster.local:4001"
        ports:
        - containerPort: 4002
          name: api
        - containerPort: 8000
          name: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: acceptor2
  namespace: paxos
spec:
  selector:
    app: acceptor2
  ports:
  - name: api
    port: 4002
    targetPort: api
  - name: monitor
    port: 8000
    targetPort: monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: acceptor3
  namespace: paxos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acceptor3
  template:
    metadata:
      labels:
        app: acceptor3
        role: acceptor
    spec:
      containers:
      - name: acceptor
        image: paxos-node:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: NODE_ID
          value: "6"
        - name: NODE_ROLE
          value: "acceptor"
        - name: PORT
          value: "4003"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          value: "paxos"
        - name: SEED_NODES
          value: "1:proposer:proposer1.paxos.svc.cluster.local:3001,4:acceptor:acceptor1.paxos.svc.cluster.local:4001,5:acceptor:acceptor2.paxos.svc.cluster.local:4002"
        ports:
        - containerPort: 4003
          name: api
        - containerPort: 8000
          name: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: acceptor3
  namespace: paxos
spec:
  selector:
    app: acceptor3
  ports:
  - name: api
    port: 4003
    targetPort: api
  - name: monitor
    port: 8000
    targetPort: monitor