version: '3.8'

services:
  # Proposers
  proposer1:
    image: paxos-node
    hostname: proposer1
    environment:
      - NODE_ID=1
      - NODE_ROLE=proposer
      - PORT=3001
      # O nó initial não precisa de seeds
      - SEED_NODES=
    ports:
      - "3001:3001"
      - "8001:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  proposer2:
    image: paxos-node
    hostname: proposer2
    environment:
      - NODE_ID=2
      - NODE_ROLE=proposer
      - PORT=3002
      # Conhece proposer1 como seed
      - SEED_NODES=1:proposer:proposer1:3001
    ports:
      - "3002:3002"
      - "8002:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1

  proposer3:
    image: paxos-node
    hostname: proposer3
    environment:
      - NODE_ID=3
      - NODE_ROLE=proposer
      - PORT=3003
      # Conhece proposer1 e proposer2 como seeds
      - SEED_NODES=1:proposer:proposer1:3001,2:proposer:proposer2:3002
    ports:
      - "3003:3003"
      - "8003:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1
      - proposer2

  # Acceptors
  acceptor1:
    image: paxos-node
    hostname: acceptor1
    environment:
      - NODE_ID=4
      - NODE_ROLE=acceptor
      - PORT=4001
      # Conhece proposer1 como seed
      - SEED_NODES=1:proposer:proposer1:3001
    ports:
      - "4001:4001"
      - "8004:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1

  acceptor2:
    image: paxos-node
    hostname: acceptor2
    environment:
      - NODE_ID=5
      - NODE_ROLE=acceptor
      - PORT=4002
      # Conhece proposer1 e acceptor1 como seeds
      - SEED_NODES=1:proposer:proposer1:3001,4:acceptor:acceptor1:4001
    ports:
      - "4002:4002"
      - "8005:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1
      - acceptor1

  acceptor3:
    image: paxos-node
    hostname: acceptor3
    environment:
      - NODE_ID=6
      - NODE_ROLE=acceptor
      - PORT=4003
      # Conhece proposer1, acceptor1, acceptor2 como seeds
      - SEED_NODES=1:proposer:proposer1:3001,4:acceptor:acceptor1:4001,5:acceptor:acceptor2:4002
    ports:
      - "4003:4003"
      - "8006:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1
      - acceptor1
      - acceptor2

  # Learners
  learner1:
    image: paxos-node
    hostname: learner1
    environment:
      - NODE_ID=7
      - NODE_ROLE=learner
      - PORT=5001
      # Conhece proposer1 e acceptor1 como seeds
      - SEED_NODES=1:proposer:proposer1:3001,4:acceptor:acceptor1:4001
    ports:
      - "5001:5001"
      - "8007:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1
      - acceptor1

  learner2:
    image: paxos-node
    hostname: learner2
    environment:
      - NODE_ID=8
      - NODE_ROLE=learner
      - PORT=5002
      # Conhece proposer1, acceptor1, learner1 como seeds
      - SEED_NODES=1:proposer:proposer1:3001,4:acceptor:acceptor1:4001,7:learner:learner1:5001
    ports:
      - "5002:5002"
      - "8008:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1
      - acceptor1
      - learner1

  # Clients
  client1:
    image: paxos-node
    hostname: client1
    environment:
      - NODE_ID=9
      - NODE_ROLE=client
      - PORT=6001
      # Conhece proposer1, acceptor1, learner1 como seeds
      - SEED_NODES=1:proposer:proposer1:3001,4:acceptor:acceptor1:4001,7:learner:learner1:5001
    ports:
      - "6001:6001"
      - "8009:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1
      - acceptor1
      - learner1

  client2:
    image: paxos-node
    hostname: client2
    environment:
      - NODE_ID=10
      - NODE_ROLE=client
      - PORT=6002
      # Conhece proposer1, acceptor1, learner1, client1 como seeds
      - SEED_NODES=1:proposer:proposer1:3001,4:acceptor:acceptor1:4001,7:learner:learner1:5001,9:client:client1:6001
    ports:
      - "6002:6002"
      - "8010:8000"
    networks:
      - paxos-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - proposer1
      - acceptor1
      - learner1
      - client1

networks:
  paxos-network:
    driver: overlay
    attachable: true